"""empty message

Revision ID: 35eff099d351
Revises: 358950079536
Create Date: 2024-03-28 20:29:20.326992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35eff099d351'
down_revision: Union[str, None] = '358950079536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descript_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('link_1', sa.String(length=250), nullable=True),
    sa.Column('link_2', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_table('descript_text')
    # ### end Alembic commands ###
