"""empty message

Revision ID: 4443ff3d28b8
Revises: d7793e2320ab
Create Date: 2024-02-18 23:15:46.166033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4443ff3d28b8'
down_revision: Union[str, None] = 'd7793e2320ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckles', 'price')
    op.drop_column('cartholders', 'price')
    op.drop_column('insoles', 'price')
    op.drop_column('wallets', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('insoles', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('cartholders', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('buckles', sa.Column('price', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
