"""empty message

Revision ID: 60bb07510a68
Revises: 4c0c81dce37b
Create Date: 2024-03-04 23:05:52.074279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60bb07510a68'
down_revision: Union[str, None] = '4c0c81dce37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purse')
    op.drop_table('buckles')
    op.drop_table('belts')
    op.drop_table('cartholders')
    op.drop_table('wallets')
    op.drop_table('insoles')
    op.alter_column('product', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    op.drop_column('product', 'url_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('product', 'price',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_table('insoles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='insoles_pkey')
    )
    op.create_table('wallets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey')
    )
    op.create_table('cartholders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cartholders_pkey')
    )
    op.create_table('belts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('length', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('width', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='belts_pkey')
    )
    op.create_table('buckles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='buckles_pkey')
    )
    op.create_table('purse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='purse_pkey')
    )
    # ### end Alembic commands ###
