"""empty message

Revision ID: b33640e55d3c
Revises: 1284e463cc2a
Create Date: 2024-02-06 22:58:27.171501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33640e55d3c'
down_revision: Union[str, None] = '1284e463cc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('belts', sa.Column('url_image', sa.String(length=500), nullable=True))
    op.add_column('buckles', sa.Column('url_image', sa.String(length=500), nullable=True))
    op.add_column('cartholders', sa.Column('url_image', sa.String(length=500), nullable=True))
    op.add_column('insoles', sa.Column('url_image', sa.String(length=500), nullable=True))
    op.add_column('purse', sa.Column('url_image', sa.String(length=500), nullable=True))
    op.add_column('wallets', sa.Column('url_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'url_image')
    op.drop_column('purse', 'url_image')
    op.drop_column('insoles', 'url_image')
    op.drop_column('cartholders', 'url_image')
    op.drop_column('buckles', 'url_image')
    op.drop_column('belts', 'url_image')
    # ### end Alembic commands ###
