"""empty message

Revision ID: db51af5d7b22
Revises: a899a6422035
Create Date: 2024-02-20 22:28:05.193386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db51af5d7b22'
down_revision: Union[str, None] = 'a899a6422035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'product_type', ['product_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'product_type_id')
    # ### end Alembic commands ###
